# ============================================================================
# CONFIGURACIÓN PARA CREAR SVM CON SERVICIO FCP USANDO API REST DE ONTAP
# ============================================================================

# Configuración del clúster
cluster:
  host: cluster1.demo.netapp.com
  username: admin
  password: Netapp1!

# Configuración de la SVM FCP
svm: 
  name: svm_1_cluster
  ipspace: Default
  aggregate: cluster1_01_SSD_1
  language: c.utf_8
  security_style: unix

  # Parámetros de modificación
  aggr_list:
    - cluster1_01_SSD_1
    - cluster1_02_SSD_1
  is_space_reporting_logical: true
  is_space_enforcement_logical: true

  # Configuración del servicio FCP
  fcp_status_admin: up  
  
  # Protocolos permitidos
  protocols:
    cifs: false
    nfs: false
    ndmp: false
    s3: false
    fcp: true
    iscsi: true

# Configuración de interfaces de red
net_interfaces:
  - lif: lif_1_cluster1
    data_protocol: fcp
    home_node: cluster1-02
    home_port: 1b
    status_admin: down 
  
  - lif: lif_2_cluster1
    data_protocol: fcp
    home_node: cluster1-02
    home_port: 0b
    status_admin: up  
  
  - lif: lif_3_cluster1
    data_protocol: fcp
    home_node: cluster1-02
    home_port: 0a
    status_admin: up  

# Configuración de la interfaz de gestión
mgmt_interface:
  lif: management
  service_policy: default-management
  address: 192.168.0.120
  netmask: 255.255.255.0
  home_node: cluster1-02
  home_port: e0c
  status_admin: up  
  auto_revert: false
  failover_group: Default




