cluster:
  host: cluster1.demo.netapp.com
  username: admin
  password: Netapp1!

svm: 
  name: ES_PRUEBA
  ipspace: Default  
  aggregate: cluster1_01_SSD_1
  language: c.utf_8
  security_style: unix

  # Se crea automáticamente. Parece q no es necesario especificarlo
  # root_volume: svm_1_cluster_root

  # Parámetros de modificación
  aggr_list:
    - cluster1_01_SSD_1
    - cluster1_02_SSD_1
  is_space_reporting_logical: true
  is_space_enforcement_logical: true
  
  # Parámetros FCP
  fcp_status_admin: true  # true = up, false = down
  
  # Configuración de protocolos (true = allowed, false = not allowed)
  protocols:
    cifs: false
    nfs: false
    ndmp: false
    s3: false
    fcp: true
    iscsi: true

# Network Interfaces - Se crea una interfaz por cada elemento de la lista
# Nota: Los puertos deben incluir el prefijo (e.g., e0a, e1a, e2a para ethernet)
net_interfaces:
  - lif: LIF1
    data_protocol: fcp
    home_node: cluster1-01
    home_port: 1a
    status_admin: true  # true = up, false = down
  
  - lif: LIF2
    data_protocol: fcp
    home_node: cluster1-02
    home_port: 1b
    status_admin: true
  
  - lif: LIF3
    data_protocol: fcp
    home_node: cluster1-01
    home_port: 0b
    status_admin: true

# Management Interface - LIF de gestión (solo una)
management_interface:
  lif: lif_fcp_mgmt
  address: 192.168.0.1
  netmask: 255.255.255.0
  home_node: cluster1-01
  home_port: e0a
  status_admin: true  # true = up, false = down
  service_policy: default-management
  failover_policy: system-defined
  firewall_policy: mgmt
  auto_revert: false
  failover_group: Default

